apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: smailandstuff-cbuv
spec:
  build:
    secrets:
      - SNYK_TOKEN
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "e32d7098-f9d6-4252-b77f-f24076f3152b"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET